Update plex-library-stats

diff --git a/plex/plex-library-stats b/plex/plex-library-stats
--- a/plex/plex-library-stats
+++ b/plex/plex-library-stats
@@ -27,6 +27,10 @@
 # 0 files missing analyzation info
 # 15491 files missing deep analyzation info.
 
+#!/bin/bash
+if pidof -o %PPID -x "$0"; then
+   exit 1
+fi
 logfile="/home/plex/logs/plexstats.log"
 db="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"
 echo "$(date "+%d.%m.%Y %T") PLEX LIBRARY STATS" | tee -a $logfile
@@ -56,21 +60,23 @@ query="select count(*) from media_items"
 result=$(sqlite3 -header -line "$db" "$query")
 echo "${result:11} files in library" | tee -a $logfile
 
-query="SELECT count(*) FROM metadata_items WHERE deleted_at is not null"
+query="select count(*) from media_items where bitrate is null"
 result=$(sqlite3 -header -line "$db" "$query")
-echo "${result:11} metadata_items marked as deleted" | tee -a $logfile
+echo "${result:11} files missing analyzation info" | tee -a $logfile
 
 query="SELECT count(*) FROM media_parts WHERE deleted_at is not null"
 result=$(sqlite3 -header -line "$db" "$query")
 echo "${result:11} media_parts marked as deleted" | tee -a $logfile
 
+query="SELECT count(*) FROM metadata_items WHERE deleted_at is not null"
+result=$(sqlite3 -header -line "$db" "$query")
+echo "${result:11} metadata_items marked as deleted" | tee -a $logfile
+
 query="SELECT count(*) FROM directories WHERE deleted_at is not null"
 result=$(sqlite3 -header -line "$db" "$query")
 echo "${result:11} directories marked as deleted" | tee -a $logfile
 
-query="select count(*) from media_items where bitrate is null"
-result=$(sqlite3 -header -line "$db" "$query")
-echo "${result:11} files missing analyzation info" | tee -a $logfile
+
 
 query="select count(*) from metadata_items meta \
                         join media_items media on media.metadata_item_id = meta.id \
